name: Create Release Archives

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@latest

    - name: Create tar.gz and .zip archives
      run: |
        # Create a temporary directory
        temp_dir=$(mktemp -d)
        cp -R $GITHUB_WORKSPACE/. $temp_dir

        # Create the archives from the temporary directory
        tar -czf release-${{ github.event.release.tag_name }}.tar.gz -C $temp_dir .
        zip -r release-${{ github.event.release.tag_name }}.zip $temp_dir/*

        # Move the archives to the workspace
        mv release-*.tar.gz release-*.zip $GITHUB_WORKSPACE

        # Clean up the temporary directory
        rm -rf $temp_dir

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: release-artifacts
        path: $GITHUB_WORKSPACE
