name: Create Release Archives

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@latest

    - name: Create tar.gz and .zip archives
      run: |
        # Exclude files or directories causing the "file changed" issue
        tar --exclude='./.git*' --exclude='./temp*' -czf release-${{ github.event.release.tag_name }}.tar.gz -C $GITHUB_WORKSPACE .
        zip -r release-${{ github.event.release.tag_name }}.zip $GITHUB_WORKSPACE/*
        mv release-*.tar.gz release-*.zip $GITHUB_WORKSPACE

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: release-artifacts
        path: $GITHUB_WORKSPACE
